config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/presentation', to: 'static#_landingpage'
  resources :currencies, path: 'crypto'
  post '/crypto/update', to: 'currencies#update'

  resources :purchases do 

  end

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <% if content_for?(:title) %>
      <%= yield :title %> |
    <% end %>
    ZedFolio
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="https://use.fontawesome.com/3250c38707.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.bundle.js" integrity="sha512-zO8oeHCxetPn1Hd9PdDleg5Tw1bAaP0YmNvPY8CwcRyUk7d7/+nyElmFrB6f7vg4f7Fv4sui1mcep8RIEShczg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.bundle.min.js" integrity="sha512-SuxO9djzjML6b9w9/I07IWnLnQhgyYVSpHZx0JV97kGBfTIsUYlWflyuW4ypnvhBrslz1yJ3R+S14fdCWmSmSA==" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.css" integrity="sha512-C7hOmCgGzihKXzyPU/z4nv97W0d9bv4ALuuEbSf6hm93myico9qa0hv4dODThvCsqQUmKmLcJmlpRmCaApr83g==" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js" integrity="sha512-hZf9Qhp3rlDJBvAKvmiG+goaaKRZA6LKUO35oK6EsM0/kjPK32Yw7URqrq3Q+Nvbbt8Usss+IekL7CRn83dYmw==" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css" integrity="sha512-/zs32ZEJh+/EO2N1b0PEdoA10JkdC3zJ8L5FTiQu82LR9S/rOQNfQN7U59U9BC12swNeRAz3HSzIL2vpp4fv3w==" crossorigin="anonymous" />
  
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_header.html.erb
<nav class="bg-gray-800 z-30">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-expanded="false" id="button">
          <span class="sr-only">Open main menu</span>
          <!-- Icon when menu is closed. -->
          <!--
            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!-- Icon when menu is open. -->
          <!--
            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex-1 flex items-center justify-center sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <%= link_to "ZedFolio", presentation_path, class:"block link text-xl h-8 w-auto text-white tracking-tight font-black" %>
        </div>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <%= link_to "Home", root_path, class: "text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to "Market", currencies_path, class: "text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <% if user_signed_in? %>
            <%= link_to "Purchases (#{current_user.portfolio.purchases.count})", purchases_path, class: "text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <% end %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <%= button_to crypto_update_path, method: :post, class: "bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white pl-2" do %>
          <i class="fa fa-refresh mr-2"></i><span class="sr-only">Update Prices</span>
        <% end %>

        <!-- Profile dropdown -->
        <div class="ml-3 relative">
          <div>
            <button class="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <img class="h-8 w-8 rounded-full" src="https://i.imgur.com/b08hxPY.png" alt="">
            </button>
          </div>

          <div id="user-dropdown" class="z-40 hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
            <p class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Last update : <br><%= Currency.last.updated_at.ago_in_words%></p>
            <% if user_signed_in? %>
              <%= link_to edit_user_registration_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem" do %>
                <i class="fa fa-user mr-2"></i><span> Edit Account</span>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "block px-4 py-2 text-sm text-red-500 hover:bg-gray-100", role: "menuitem" do %>
                <i class="fa fa-times-circle mr-2"></i><span> Log Out</span>
              <% end %>
            <% else %>
              <%= link_to new_user_session_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem" do %>
                <i class="fa fa-user mr-2"></i><span> Login</span>
              <% end %>
              <%= link_to new_user_registration_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem" do %>
                <i class="fa fa-edit mr-2"></i><span> Sign Up</span>
              <% end %>
            <% end %>
            <a class="block px-4 py-2 text-sm font-black text-gray-700 hover:bg-gray-100 " role="menuitem" id="theme-toggler">Theme 🌚</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!--
    Mobile menu, toggle classes based on menu state.

    Menu open: "block", Menu closed: "hidden"
  -->
  <div id="menu-mobile" class="hidden sm:hidden">
    <div class="px-2 pt-2 pb-3 space-y-1">
      <%= link_to "Home", root_path, class: "text-white block px-3 py-2 rounded-md text-base font-medium" %>
      <%= link_to "Market", currencies_path, class: "text-white block px-3 py-2 rounded-md text-base font-medium" %>
    <% if user_signed_in? %>
      <%= link_to "Purchases (#{current_user.portfolio.purchases.count})", purchases_path, class: "text-white block px-3 py-2 rounded-md text-base font-medium" %>
    <% end %>
    </div>
  </div>
</nav>


<script>

  // Navbar Toggler
  var menuButton = document.getElementById('button'); // Assumes element with id='button'

  menuButton.onclick = function() {
    var element = document.getElementById('menu-mobile');  // Assumes element has id of #navbar
    element.classList.toggle('hidden');
  }

  window.addEventListener("mouseup", menuHide);

  function menuHide(){  
      var element = document.getElementById('menu-mobile');  // Assumes element has id of #navbar
      element.classList.add('hidden');
  }

  // Profile Menu Toggler
  var profileButton = document.getElementById('user-menu'); // Assumes element with id='button'

  profileButton.onclick = function() {
      var element = document.getElementById('user-dropdown');  // Assumes element has id of #navbar
      element.classList.toggle('hidden');
  }

  window.addEventListener("mouseup", dropHide);

  function dropHide(){  
      var element = document.getElementById('user-dropdown');  // Assumes element has id of #navbar
      element.classList.add('hidden');
  }

  // Dark/Light Theme Toggler
  var themeToggler = document.querySelector('#theme-toggler');
  var currentTheme = localStorage.getItem('theme');
  var pageTheme = document.querySelector('.html');

  var isDark = true;

  if (currentTheme == 'dark') {
    pageTheme.classList.add('dark');
    themeToggler.innerText = 'Change Theme 🌞';
  } else {
    themeToggler.innerText = 'Change Theme 🌚';
  }

  function themeMode() {
    isDark = !isDark;
    // if (isDark == true) {
    //   themeToggler.innerText = '🌞'
    // } else {
    //   themeToggler.innerText = '🌚'
    // }
    // isDark ? (themeToggler.innerText = '🌞') : (themeToggler.innerText = '🌚');
    pageTheme.classList.toggle('dark');

    let theme = 'light';
    themeToggler.innerText = 'Change Theme 🌚'
    if (pageTheme.classList.contains('dark')) {
      theme = 'dark';
      themeToggler.innerText = 'Change Theme 🌞'
    }
    localStorage.setItem('theme', theme);
  }

  themeToggler.addEventListener('click', themeMode);
  </script>