config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/presentation', to: 'static#_landingpage'
  resources :currencies, path: 'crypto'
  post '/crypto/update', to: 'currencies#update'

  resources :purchases do 

  end

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index

    if current_user
      @purchases = current_user.portfolio.purchases
    end

  end
end

app/views/home/_home_page.erb
<div class="max-w-7xl mx-auto mt-16 text-center">
  <h1 class="mb-4 text-5xl font-black dark:text-gray-100 transition duration-500">Your cryptocurrencies traces and holding</h1>
  <h2 class="mb-4 text-3xl font-bold text-indigo-600 dark:text-blue-400 transition duration-500">Your portfolio total value : <%= number_to_currency(current_user.portfolio.total.round(4)) %> </h2>
  <h3 class="mb-4 text-2xl font-bold text-indigo-600 dark:text-blue-400 transition duration-500">Your total invested : <%= number_to_currency(current_user.portfolio.total_invested.round(4)) %> </h3>

  <%= link_to new_purchase_path, class: "bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center" do %>
    <i class="fa fa-plus mr-2 my-2"></i><span> Add a purchase</span>
  <% end %>

  <h2 class="mt-6 mb-4 text-4xl font-bold text-gray-600 dark:text-gray-100 transition duration-500">Your 10 last purchases</h2>

  <div class="flex flex-col my-8">
    <div class="my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50 dark:bg-gray-700 dark:text-gray-100 transition duration-500">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-200 uppercase tracking-wider transition duration-500">
                  Crypto
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-200 uppercase tracking-wider transition duration-500">
                  Buying Price
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-200 uppercase tracking-wider transition duration-500">
                  Amount
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-200 uppercase tracking-wider transition duration-500">
                  Purchase Date
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-200 uppercase tracking-wider transition duration-500">
                  Total Invested
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <% @purchases.order('purchasedate').first(10).each do |purchase| %>
                <tr>
                  <td class="px-6 py-4 whitespace-nowrap dark:bg-gray-200 transition duration-500">
                    <div class="flex items-center">
                      <div class="flex-shrink-0 h-10 w-10">
                        <img class="h-10 w-10 rounded-full" src="<%= Currency.find_by('name':purchase.crypto).logo%>" alt="">
                      </div>
                      <div class="ml-4">
                        <div class="text-sm font-medium text-blue-600">
                          <a href="<%= currency_path(Currency.find_by("name": purchase.crypto).slug) %>"><%= purchase.crypto %></a>
                        </div>
                        <div class="text-sm text-gray-500 text-left">
                          <%= Currency.find_by("name": purchase.crypto).currency_symbol %>
                        </div>
                      </div>
                    </div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap dark:bg-gray-200 transition duration-500">
                    <div class="text-sm text-gray-900"><%= number_to_currency(purchase.price.round(4), :precision => 4) %></div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap dark:bg-gray-200 transition duration-500">
                    <div class="text-sm text-gray-900"><%= number_with_delimiter(purchase.number.round(3), :precision => 4, :delimiter => ',') %></div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap dark:bg-gray-200 text-sm text-gray-500 transition duration-500">
                    <%= purchase.purchasedate.strftime('%d.%m.%y at %H:%M:%S') %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap dark:bg-gray-200 transition duration-500">
                    <%= number_to_currency((purchase.number * purchase.price).round(4), :precision => 4) %>
                  </td>
                </tr>
              <% end %>
                <tr>
                  <td class="px-6 py-4 whitespace-nowrap dark:bg-gray-200 transition duration-500">
                    <%= link_to "See all.. (#{current_user.portfolio.purchases.count})", purchases_path, class: "btn border-gray-400 rounded whitespace-nowrap " %>
                  </td>
                  <td class="dark:bg-gray-200 transition duration-500"></td>
                  <td class="whitespace-nowrap dark:bg-gray-200 transition duration-500"></td>
                  <td class="whitespace-nowrap dark:bg-gray-200 transition duration-500"></td>
                  <td class="whitespace-nowrap dark:bg-gray-200 transition duration-500"></td>
                </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= render "home_page", purchase: @purchases %>

<% else %>
  <%= render 'static/landingpage' %>
<% end %>